### ISSUE TITLE
Tracking issue for submitting process

### ISSUE THREAD

**Issue by Nauxuron** [Nauxuron/ruma-appservice-api#1]
There are a couple of things I want to mention before submitting this repository for review:

- The endpoints have a `v1` path instead of `r0` like the client API endpoints. The federation API also has `v1` (and even `v2`) endpoints, but the ruma-federation-api repository is still empty. I chose to create a `v1` module, but this doesn't correspond cleanly with `r0.x.x` versions of the specification.
- The entire ` /_matrix/app/v1/thirdparty/*` endpoint is basically 99% the same as the ` /_matrix/client/r0/thirdparty/*` endpoint, which still needs to be implemented (ruma/ruma-client#21).
I thought it would be best to do the client endpoint first and get any discussion and possible new types for identifiers or events out of the way. Then it will be fairly trivial to define the same endpoints for application services.
- The application service specification also defines some extensions to the client API (https://matrix.org/docs/spec/application_service/r0.1.2#client-server-api-extensions). Currently, this consists of one extra endpoint. However, it also allows application services to act as a user ID in their user namespaces. This requires a `user_id` query parameter, and this parameter needs to be implemented on all client API endpoints.
- CI needs to be configured for this repository, but I thought I would do that once it is under the ruma organization.
- There needs to be a crate for `ruma-appservice-api` registered and possibly also for `ruma-appservice` once I (or someone else) wants to implement a high level wrapper over this crate.

**Comment by jplatte** [comment]
Looking good! The only thing I've noticed is that you should use `EventResult` in `v1::event::push_events`. If you can move this to ruma now (not sure whether GitHub allows you to move repos to organizations you're not a part of), feel free to do so. I'll make you a collaborator so you can keep working on the master branch, and also enable travis.ci once the `.travis.yml` is present.

**Comment by Nauxuron** [comment]
> Looking good! The only thing I've noticed is that you should use `EventResult` in `v1::event::push_events`. 

Ah, that means that this crate can only be used on the homeserver side for now.

> If you can move this to ruma now (not sure whether GitHub allows you to move repos to organizations you're not a part of), feel free to do so.

I can't do that, you need permission to create repos in that organization.

> I'll make you a collaborator so you can keep working on the master branch, and also enable travis.ci once the `.travis.yml` is present.

Thanks, that would be great! :smile:

**Comment by jplatte** [comment]
Do you plan to use this API on the request-receiving side (which I understand is not the homeserver here)? If so, that would be another reason to work on updating ruma-api to work for both client and server.

**Comment by Nauxuron** [comment]
Yes, I think it would be nice if you could write application services in Rust as well. Application services also require a web framework, so I presume that we will choose the same web framework as for the homeserver.

It is indeed another reason to update ruma-api, however I would say that the federation API needs it more.

I think supporting application services on the homeserver side shouldn't be super high priority, as a homeserver can work without and it doesn't affect client-server and server-server functionality, because it's completely local to the homeserver.

Can you create this repo in the ruma organization and give me write access? I can then push my work there.

**Comment by jplatte** [comment]
Unfortunately I can't. I expected that I could, but I don't have premission to create repos in the ruma org. Will ask Jimmy to create it.

**Comment by jplatte** [comment]
We now have [ruma/ruma-appservice-api](https://github.com/ruma/ruma-appservice-api). I can't see whether you have access to it, but you probably got an invite email if that is the case. Otherwise, you can maintain this repo as a fork and I'll pull in your changes.
